backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "home-sections"
    label: "Home Section"
    files:
      - name: "hero"
        label: "Hero"
        file: "content/home-hero.json"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Call to Action"
            name: "cta"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Action", name: "action", widget: "string" }
